// Dados dos e-books da plataforma e-booksjá

export type Ebook = {
  id: number;
  title: string;
  author: string;
  category: string;
  cover: string;
  description: string;
  pages: number;
  price: number;
  purchased: boolean;
};

export const EBOOKS_DATA: Ebook[] = [
  // PROGRAMAÇÃO (50 e-books)
  {
    id: 1,
    title: "Dominando JavaScript Moderno",
    author: "Carlos Silva",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=400&h=600&fit=crop",
    description: "Aprenda JavaScript do zero ao avançado com exemplos práticos e projetos reais.",
    pages: 320,
    price: 4.99,
    purchased: false,
  },
  {
    id: 2,
    title: "Python para Data Science",
    author: "Lucas Ferreira",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&h=600&fit=crop",
    description: "Análise de dados e machine learning com Python.",
    pages: 380,
    price: 4.99,
    purchased: false,
  },
  {
    id: 3,
    title: "React e Next.js Avançado",
    author: "Marina Costa",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&h=600&fit=crop",
    description: "Construa aplicações web modernas com React e Next.js.",
    pages: 450,
    price: 4.99,
    purchased: false,
  },
  {
    id: 4,
    title: "TypeScript do Zero ao Pro",
    author: "Rafael Santos",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=400&h=600&fit=crop",
    description: "Domine TypeScript e escreva código mais seguro e escalável.",
    pages: 290,
    price: 4.99,
    purchased: false,
  },
  {
    id: 5,
    title: "Node.js e APIs RESTful",
    author: "Thiago Almeida",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=600&fit=crop",
    description: "Crie APIs robustas e escaláveis com Node.js.",
    pages: 340,
    price: 4.99,
    purchased: false,
  },
  {
    id: 6,
    title: "Banco de Dados SQL Completo",
    author: "Patricia Lima",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=400&h=600&fit=crop",
    description: "Domine SQL e otimize suas consultas de banco de dados.",
    pages: 310,
    price: 4.99,
    purchased: false,
  },
  {
    id: 7,
    title: "Git e GitHub na Prática",
    author: "Bruno Oliveira",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=400&h=600&fit=crop",
    description: "Controle de versão profissional para desenvolvedores.",
    pages: 180,
    price: 4.99,
    purchased: false,
  },
  {
    id: 8,
    title: "Docker e Kubernetes",
    author: "André Martins",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1605745341112-85968b19335b?w=400&h=600&fit=crop",
    description: "Containerização e orquestração de aplicações modernas.",
    pages: 420,
    price: 4.99,
    purchased: false,
  },
  {
    id: 9,
    title: "Algoritmos e Estruturas de Dados",
    author: "Juliana Rocha",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=400&h=600&fit=crop",
    description: "Fundamentos essenciais para programadores.",
    pages: 480,
    price: 4.99,
    purchased: false,
  },
  {
    id: 10,
    title: "Clean Code em JavaScript",
    author: "Fernando Costa",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=400&h=600&fit=crop",
    description: "Escreva código limpo, legível e manutenível.",
    pages: 260,
    price: 4.99,
    purchased: false,
  },
  {
    id: 11,
    title: "Vue.js 3 Completo",
    author: "Camila Souza",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1593720213428-28a5b9e94613?w=400&h=600&fit=crop",
    description: "Framework progressivo para interfaces de usuário.",
    pages: 350,
    price: 4.99,
    purchased: false,
  },
  {
    id: 12,
    title: "Angular Moderno",
    author: "Ricardo Mendes",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&h=600&fit=crop",
    description: "Desenvolvimento de aplicações enterprise com Angular.",
    pages: 410,
    price: 4.99,
    purchased: false,
  },
  {
    id: 13,
    title: "PHP e Laravel Avançado",
    author: "Gustavo Pereira",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1599507593499-a3f7d7d97667?w=400&h=600&fit=crop",
    description: "Desenvolvimento web profissional com PHP e Laravel.",
    pages: 390,
    price: 4.99,
    purchased: false,
  },
  {
    id: 14,
    title: "Ruby on Rails Completo",
    author: "Beatriz Santos",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&h=600&fit=crop",
    description: "Framework web elegante e produtivo.",
    pages: 370,
    price: 4.99,
    purchased: false,
  },
  {
    id: 15,
    title: "Go Programming",
    author: "Leonardo Dias",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=400&h=600&fit=crop",
    description: "Linguagem moderna para sistemas distribuídos.",
    pages: 330,
    price: 4.99,
    purchased: false,
  },
  {
    id: 16,
    title: "Rust para Iniciantes",
    author: "Mariana Ferreira",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=400&h=600&fit=crop",
    description: "Programação segura e de alta performance.",
    pages: 360,
    price: 4.99,
    purchased: false,
  },
  {
    id: 17,
    title: "C# e .NET Core",
    author: "Paulo Henrique",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=600&fit=crop",
    description: "Desenvolvimento multiplataforma com .NET.",
    pages: 400,
    price: 4.99,
    purchased: false,
  },
  {
    id: 18,
    title: "Java Spring Boot",
    author: "Rodrigo Alves",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=400&h=600&fit=crop",
    description: "Aplicações Java modernas e escaláveis.",
    pages: 440,
    price: 4.99,
    purchased: false,
  },
  {
    id: 19,
    title: "Kotlin para Android",
    author: "Isabela Martins",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=600&fit=crop",
    description: "Desenvolvimento de apps Android modernos.",
    pages: 380,
    price: 4.99,
    purchased: false,
  },
  {
    id: 20,
    title: "Swift e iOS Development",
    author: "Gabriel Costa",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=400&h=600&fit=crop",
    description: "Crie aplicativos incríveis para iPhone e iPad.",
    pages: 420,
    price: 4.99,
    purchased: false,
  },
  {
    id: 21,
    title: "Flutter Cross-Platform",
    author: "Amanda Silva",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=400&h=600&fit=crop",
    description: "Um código, múltiplas plataformas com Flutter.",
    pages: 390,
    price: 4.99,
    purchased: false,
  },
  {
    id: 22,
    title: "React Native Avançado",
    author: "Vinícius Rocha",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=400&h=600&fit=crop",
    description: "Apps mobile com JavaScript e React.",
    pages: 370,
    price: 4.99,
    purchased: false,
  },
  {
    id: 23,
    title: "GraphQL Completo",
    author: "Larissa Mendes",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=600&fit=crop",
    description: "APIs modernas e eficientes com GraphQL.",
    pages: 310,
    price: 4.99,
    purchased: false,
  },
  {
    id: 24,
    title: "MongoDB e NoSQL",
    author: "Diego Santos",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=400&h=600&fit=crop",
    description: "Bancos de dados não relacionais na prática.",
    pages: 290,
    price: 4.99,
    purchased: false,
  },
  {
    id: 25,
    title: "Redis e Cache Distribuído",
    author: "Fernanda Lima",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=600&fit=crop",
    description: "Otimize performance com cache inteligente.",
    pages: 240,
    price: 4.99,
    purchased: false,
  },
  {
    id: 26,
    title: "Microserviços com Node.js",
    author: "Henrique Oliveira",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=600&fit=crop",
    description: "Arquitetura de microserviços escalável.",
    pages: 430,
    price: 4.99,
    purchased: false,
  },
  {
    id: 27,
    title: "Testes Automatizados",
    author: "Carolina Dias",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=400&h=600&fit=crop",
    description: "TDD, BDD e testes de integração.",
    pages: 320,
    price: 4.99,
    purchased: false,
  },
  {
    id: 28,
    title: "CI/CD com GitHub Actions",
    author: "Marcos Ferreira",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=400&h=600&fit=crop",
    description: "Automatize deploy e integração contínua.",
    pages: 270,
    price: 4.99,
    purchased: false,
  },
  {
    id: 29,
    title: "AWS para Desenvolvedores",
    author: "Juliana Costa",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=600&fit=crop",
    description: "Cloud computing com Amazon Web Services.",
    pages: 460,
    price: 4.99,
    purchased: false,
  },
  {
    id: 30,
    title: "Azure DevOps",
    author: "Roberto Silva",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=600&fit=crop",
    description: "Desenvolvimento e deploy na nuvem Microsoft.",
    pages: 410,
    price: 4.99,
    purchased: false,
  },
  {
    id: 31,
    title: "Google Cloud Platform",
    author: "Patrícia Almeida",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=600&fit=crop",
    description: "Infraestrutura escalável com GCP.",
    pages: 390,
    price: 4.99,
    purchased: false,
  },
  {
    id: 32,
    title: "Serverless Architecture",
    author: "Lucas Mendes",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=600&fit=crop",
    description: "Aplicações sem servidor na nuvem.",
    pages: 330,
    price: 4.99,
    purchased: false,
  },
  {
    id: 33,
    title: "Segurança em Aplicações Web",
    author: "Renata Santos",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=600&fit=crop",
    description: "Proteja suas aplicações contra ataques.",
    pages: 380,
    price: 4.99,
    purchased: false,
  },
  {
    id: 34,
    title: "OAuth e Autenticação",
    author: "Felipe Rocha",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=600&fit=crop",
    description: "Sistemas de autenticação seguros.",
    pages: 290,
    price: 4.99,
    purchased: false,
  },
  {
    id: 35,
    title: "WebSockets em Tempo Real",
    author: "Bruna Lima",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=600&fit=crop",
    description: "Comunicação bidirecional em tempo real.",
    pages: 260,
    price: 4.99,
    purchased: false,
  },
  {
    id: 36,
    title: "Elasticsearch e Busca",
    author: "André Oliveira",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=400&h=600&fit=crop",
    description: "Busca e análise de dados em escala.",
    pages: 340,
    price: 4.99,
    purchased: false,
  },
  {
    id: 37,
    title: "RabbitMQ e Mensageria",
    author: "Cristina Martins",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=600&fit=crop",
    description: "Sistemas distribuídos com filas de mensagens.",
    pages: 310,
    price: 4.99,
    purchased: false,
  },
  {
    id: 38,
    title: "Blockchain com JavaScript",
    author: "Thiago Costa",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&h=600&fit=crop",
    description: "Entenda e implemente blockchain.",
    pages: 370,
    price: 4.99,
    purchased: false,
  },
  {
    id: 39,
    title: "Machine Learning com Python",
    author: "Daniela Silva",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=600&fit=crop",
    description: "Inteligência artificial na prática.",
    pages: 490,
    price: 4.99,
    purchased: false,
  },
  {
    id: 40,
    title: "Deep Learning e Redes Neurais",
    author: "Rodrigo Ferreira",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=600&fit=crop",
    description: "Redes neurais profundas com TensorFlow.",
    pages: 520,
    price: 4.99,
    purchased: false,
  },
  {
    id: 41,
    title: "Computer Vision com OpenCV",
    author: "Vanessa Almeida",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=600&fit=crop",
    description: "Processamento de imagens e visão computacional.",
    pages: 410,
    price: 4.99,
    purchased: false,
  },
  {
    id: 42,
    title: "NLP - Processamento de Linguagem",
    author: "Eduardo Santos",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=600&fit=crop",
    description: "Análise e processamento de texto com IA.",
    pages: 450,
    price: 4.99,
    purchased: false,
  },
  {
    id: 43,
    title: "Web Scraping com Python",
    author: "Aline Rocha",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&h=600&fit=crop",
    description: "Extraia dados da web automaticamente.",
    pages: 280,
    price: 4.99,
    purchased: false,
  },
  {
    id: 44,
    title: "Automação com Selenium",
    author: "Fábio Mendes",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&h=600&fit=crop",
    description: "Automatize tarefas web com Selenium.",
    pages: 250,
    price: 4.99,
    purchased: false,
  },
  {
    id: 45,
    title: "Performance Web Optimization",
    author: "Letícia Costa",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=600&fit=crop",
    description: "Otimize velocidade e performance web.",
    pages: 310,
    price: 4.99,
    purchased: false,
  },
  {
    id: 46,
    title: "PWA - Progressive Web Apps",
    author: "Gustavo Lima",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=600&fit=crop",
    description: "Apps web que funcionam offline.",
    pages: 290,
    price: 4.99,
    purchased: false,
  },
  {
    id: 47,
    title: "WebAssembly Moderno",
    author: "Mariana Dias",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=600&fit=crop",
    description: "Performance nativa no navegador.",
    pages: 340,
    price: 4.99,
    purchased: false,
  },
  {
    id: 48,
    title: "Electron - Apps Desktop",
    author: "Rafael Oliveira",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&h=600&fit=crop",
    description: "Aplicações desktop com web technologies.",
    pages: 360,
    price: 4.99,
    purchased: false,
  },
  {
    id: 49,
    title: "Regex - Expressões Regulares",
    author: "Camila Ferreira",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=400&h=600&fit=crop",
    description: "Domine padrões e validações com regex.",
    pages: 190,
    price: 4.99,
    purchased: false,
  },
  {
    id: 50,
    title: "Design Patterns em JavaScript",
    author: "Bruno Silva",
    category: "Programação",
    cover: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=400&h=600&fit=crop",
    description: "Padrões de projeto para código escalável.",
    pages: 380,
    price: 4.99,
    purchased: false,
  },

  // MARKETING (40 e-books)
  {
    id: 51,
    title: "Marketing Digital para Iniciantes",
    author: "Ana Costa",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1432888622747-4eb9a8f2c293?w=400&h=600&fit=crop",
    description: "Estratégias comprovadas para crescer seu negócio online.",
    pages: 280,
    price: 4.99,
    purchased: false,
  },
  {
    id: 52,
    title: "Copywriting Persuasivo",
    author: "Fernanda Lima",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400&h=600&fit=crop",
    description: "Escreva textos que vendem e convertem.",
    pages: 220,
    price: 4.99,
    purchased: false,
  },
  {
    id: 53,
    title: "SEO Avançado",
    author: "Pedro Almeida",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1432888622747-4eb9a8f2c293?w=400&h=600&fit=crop",
    description: "Domine o Google e ranqueie no topo.",
    pages: 340,
    price: 4.99,
    purchased: false,
  },
  {
    id: 54,
    title: "Google Ads Completo",
    author: "Juliana Santos",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=600&fit=crop",
    description: "Anúncios lucrativos no Google.",
    pages: 310,
    price: 4.99,
    purchased: false,
  },
  {
    id: 55,
    title: "Facebook Ads Mastery",
    author: "Ricardo Mendes",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400&h=600&fit=crop",
    description: "Campanhas de alto ROI no Facebook.",
    pages: 290,
    price: 4.99,
    purchased: false,
  },
  {
    id: 56,
    title: "Instagram Marketing",
    author: "Beatriz Costa",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=400&h=600&fit=crop",
    description: "Cresça sua marca no Instagram.",
    pages: 260,
    price: 4.99,
    purchased: false,
  },
  {
    id: 57,
    title: "TikTok para Negócios",
    author: "Lucas Ferreira",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=400&h=600&fit=crop",
    description: "Viralização e vendas no TikTok.",
    pages: 240,
    price: 4.99,
    purchased: false,
  },
  {
    id: 58,
    title: "LinkedIn B2B Marketing",
    author: "Mariana Rocha",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1611944212129-29977ae1398c?w=400&h=600&fit=crop",
    description: "Vendas corporativas no LinkedIn.",
    pages: 270,
    price: 4.99,
    purchased: false,
  },
  {
    id: 59,
    title: "Email Marketing Lucrativo",
    author: "Gabriel Silva",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=400&h=600&fit=crop",
    description: "Construa lista e venda por email.",
    pages: 250,
    price: 4.99,
    purchased: false,
  },
  {
    id: 60,
    title: "Marketing de Conteúdo",
    author: "Amanda Oliveira",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1432888622747-4eb9a8f2c293?w=400&h=600&fit=crop",
    description: "Atraia clientes com conteúdo de valor.",
    pages: 320,
    price: 4.99,
    purchased: false,
  },
  // Continua com mais 30 e-books de Marketing...
  {
    id: 61,
    title: "Funil de Vendas Digital",
    author: "Thiago Costa",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=600&fit=crop",
    description: "Construa funis que convertem.",
    pages: 300,
    price: 4.99,
    purchased: false,
  },
  {
    id: 62,
    title: "Growth Hacking",
    author: "Carolina Dias",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=600&fit=crop",
    description: "Crescimento acelerado com baixo custo.",
    pages: 280,
    price: 4.99,
    purchased: false,
  },
  {
    id: 63,
    title: "Branding e Posicionamento",
    author: "Felipe Almeida",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1542744094-3a31f272c490?w=400&h=600&fit=crop",
    description: "Construa uma marca memorável.",
    pages: 290,
    price: 4.99,
    purchased: false,
  },
  {
    id: 64,
    title: "Marketing de Influência",
    author: "Larissa Santos",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=400&h=600&fit=crop",
    description: "Parcerias lucrativas com influencers.",
    pages: 230,
    price: 4.99,
    purchased: false,
  },
  {
    id: 65,
    title: "Storytelling para Marcas",
    author: "Diego Martins",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400&h=600&fit=crop",
    description: "Conte histórias que vendem.",
    pages: 210,
    price: 4.99,
    purchased: false,
  },
  {
    id: 66,
    title: "Marketing de Afiliados",
    author: "Renata Lima",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=600&fit=crop",
    description: "Ganhe comissões promovendo produtos.",
    pages: 260,
    price: 4.99,
    purchased: false,
  },
  {
    id: 67,
    title: "Análise de Métricas",
    author: "Henrique Rocha",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=600&fit=crop",
    description: "Tome decisões baseadas em dados.",
    pages: 310,
    price: 4.99,
    purchased: false,
  },
  {
    id: 68,
    title: "Google Analytics 4",
    author: "Cristina Ferreira",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=600&fit=crop",
    description: "Domine a nova versão do Analytics.",
    pages: 280,
    price: 4.99,
    purchased: false,
  },
  {
    id: 69,
    title: "CRM e Automação",
    author: "André Oliveira",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=600&fit=crop",
    description: "Automatize relacionamento com clientes.",
    pages: 290,
    price: 4.99,
    purchased: false,
  },
  {
    id: 70,
    title: "Chatbots para Vendas",
    author: "Vanessa Silva",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=400&h=600&fit=crop",
    description: "Atendimento automatizado que converte.",
    pages: 240,
    price: 4.99,
    purchased: false,
  },
  {
    id: 71,
    title: "Remarketing Avançado",
    author: "Eduardo Costa",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=600&fit=crop",
    description: "Recupere visitantes e aumente vendas.",
    pages: 250,
    price: 4.99,
    purchased: false,
  },
  {
    id: 72,
    title: "Marketing Omnichannel",
    author: "Aline Mendes",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=600&fit=crop",
    description: "Integre todos os canais de venda.",
    pages: 320,
    price: 4.99,
    purchased: false,
  },
  {
    id: 73,
    title: "Neuromarketing",
    author: "Fábio Santos",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=600&fit=crop",
    description: "Psicologia aplicada ao marketing.",
    pages: 270,
    price: 4.99,
    purchased: false,
  },
  {
    id: 74,
    title: "Marketing Sensorial",
    author: "Letícia Almeida",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1542744094-3a31f272c490?w=400&h=600&fit=crop",
    description: "Engaje os sentidos dos clientes.",
    pages: 230,
    price: 4.99,
    purchased: false,
  },
  {
    id: 75,
    title: "Marketing Verde",
    author: "Gustavo Rocha",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=400&h=600&fit=crop",
    description: "Sustentabilidade como diferencial.",
    pages: 240,
    price: 4.99,
    purchased: false,
  },
  {
    id: 76,
    title: "Lançamento de Produtos",
    author: "Mariana Lima",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=600&fit=crop",
    description: "Estratégias de lançamento de sucesso.",
    pages: 300,
    price: 4.99,
    purchased: false,
  },
  {
    id: 77,
    title: "Marketing Local",
    author: "Rafael Dias",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=400&h=600&fit=crop",
    description: "Domine seu mercado local.",
    pages: 220,
    price: 4.99,
    purchased: false,
  },
  {
    id: 78,
    title: "Vídeo Marketing",
    author: "Camila Ferreira",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?w=400&h=600&fit=crop",
    description: "Crie vídeos que engajam e vendem.",
    pages: 260,
    price: 4.99,
    purchased: false,
  },
  {
    id: 79,
    title: "Podcast Marketing",
    author: "Bruno Oliveira",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=400&h=600&fit=crop",
    description: "Cresça sua audiência com podcasts.",
    pages: 230,
    price: 4.99,
    purchased: false,
  },
  {
    id: 80,
    title: "Webinars que Vendem",
    author: "Daniela Silva",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=400&h=600&fit=crop",
    description: "Apresentações online lucrativas.",
    pages: 250,
    price: 4.99,
    purchased: false,
  },
  {
    id: 81,
    title: "Marketing de Eventos",
    author: "Rodrigo Costa",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=600&fit=crop",
    description: "Organize eventos memoráveis.",
    pages: 270,
    price: 4.99,
    purchased: false,
  },
  {
    id: 82,
    title: "Programas de Fidelidade",
    author: "Vanessa Almeida",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=600&fit=crop",
    description: "Retenha e fidelize clientes.",
    pages: 240,
    price: 4.99,
    purchased: false,
  },
  {
    id: 83,
    title: "Marketing de Guerrilha",
    author: "Eduardo Mendes",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400&h=600&fit=crop",
    description: "Ações criativas de baixo custo.",
    pages: 210,
    price: 4.99,
    purchased: false,
  },
  {
    id: 84,
    title: "Marketing Viral",
    author: "Aline Santos",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=400&h=600&fit=crop",
    description: "Crie campanhas que viralizam.",
    pages: 230,
    price: 4.99,
    purchased: false,
  },
  {
    id: 85,
    title: "Marketing Conversacional",
    author: "Fábio Rocha",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=400&h=600&fit=crop",
    description: "Venda através de conversas.",
    pages: 220,
    price: 4.99,
    purchased: false,
  },
  {
    id: 86,
    title: "Marketing de Experiência",
    author: "Letícia Costa",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1542744094-3a31f272c490?w=400&h=600&fit=crop",
    description: "Crie experiências inesquecíveis.",
    pages: 260,
    price: 4.99,
    purchased: false,
  },
  {
    id: 87,
    title: "Marketing para Startups",
    author: "Gustavo Lima",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=400&h=600&fit=crop",
    description: "Cresça sua startup rapidamente.",
    pages: 290,
    price: 4.99,
    purchased: false,
  },
  {
    id: 88,
    title: "Marketing para E-commerce",
    author: "Mariana Dias",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=600&fit=crop",
    description: "Venda mais em lojas virtuais.",
    pages: 310,
    price: 4.99,
    purchased: false,
  },
  {
    id: 89,
    title: "Marketing para SaaS",
    author: "Rafael Oliveira",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=600&fit=crop",
    description: "Estratégias para software como serviço.",
    pages: 320,
    price: 4.99,
    purchased: false,
  },
  {
    id: 90,
    title: "Marketing Internacional",
    author: "Camila Silva",
    category: "Marketing",
    cover: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=400&h=600&fit=crop",
    description: "Expanda para mercados globais.",
    pages: 340,
    price: 4.99,
    purchased: false,
  },

  // FINANÇAS (35 e-books) - Adicionando apenas alguns exemplos
  {
    id: 91,
    title: "Finanças Pessoais Inteligentes",
    author: "Roberto Almeida",
    category: "Finanças",
    cover: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=400&h=600&fit=crop",
    description: "Como organizar suas finanças e construir patrimônio.",
    pages: 240,
    price: 4.99,
    purchased: false,
  },
  {
    id: 92,
    title: "Investimentos para Iniciantes",
    author: "Patricia Santos",
    category: "Finanças",
    cover: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=400&h=600&fit=crop",
    description: "Comece a investir do jeito certo.",
    pages: 280,
    price: 4.99,
    purchased: false,
  },
  // ... Adicione os outros 33 e-books de Finanças aqui

  // DESIGN (30 e-books) - Adicionando apenas alguns exemplos
  {
    id: 126,
    title: "Design Thinking na Prática",
    author: "Juliana Martins",
    category: "Design",
    cover: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=400&h=600&fit=crop",
    description: "Metodologia completa para inovação e resolução de problemas.",
    pages: 195,
    price: 4.99,
    purchased: false,
  },
  {
    id: 127,
    title: "UI/UX Design Moderno",
    author: "Pedro Santos",
    category: "Design",
    cover: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=600&fit=crop",
    description: "Crie interfaces que encantam usuários.",
    pages: 340,
    price: 4.99,
    purchased: false,
  },
  // ... Adicione os outros 28 e-books de Design aqui

  // DESENVOLVIMENTO PESSOAL (30 e-books) - Adicionando apenas alguns exemplos
  {
    id: 156,
    title: "Inteligência Emocional",
    author: "Mariana Oliveira",
    category: "Desenvolvimento Pessoal",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=600&fit=crop",
    description: "Desenvolva suas habilidades emocionais e relacionamentos.",
    pages: 265,
    price: 4.99,
    purchased: false,
  },
  {
    id: 157,
    title: "Hábitos Poderosos",
    author: "Lucas Mendes",
    category: "Desenvolvimento Pessoal",
    cover: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400&h=600&fit=crop",
    description: "Transforme sua vida com pequenas mudanças.",
    pages: 280,
    price: 4.99,
    purchased: false,
  },
  // ... Adicione os outros 28 e-books de Desenvolvimento Pessoal aqui

  // PRODUTIVIDADE (25 e-books) - Adicionando apenas alguns exemplos
  {
    id: 186,
    title: "Produtividade Máxima",
    author: "Pedro Santos",
    category: "Produtividade",
    cover: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400&h=600&fit=crop",
    description: "Técnicas comprovadas para multiplicar sua produtividade.",
    pages: 210,
    price: 4.99,
    purchased: false,
  },
  {
    id: 187,
    title: "GTD - Getting Things Done",
    author: "Ricardo Mendes",
    category: "Produtividade",
    cover: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400&h=600&fit=crop",
    description: "Organize sua vida e trabalho.",
    pages: 280,
    price: 4.99,
    purchased: false,
  },
  // ... Adicione os outros 23 e-books de Produtividade aqui
];

export const CATEGORIES = [
  "Programação",
  "Marketing",
  "Finanças",
  "Design",
  "Desenvolvimento Pessoal",
  "Produtividade",
] as const;

export type Category = typeof CATEGORIES[number];
